services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile.drupal.coolify
    environment:
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-database}
      - DB_PASSWORD=${DB_PASSWORD:-drupal10}
      - DB_USER=${DB_USER:-drupal10}
      - DB_HASH_SALT=${DB_HASH_SALT:-c2GsV7Wo7znoTha0FMp6dTMwdeqMBqxxr-wSWUjgu17dreCRbbatVkIkcTm1KgmksptafNBMw}
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -f http://localhost:80 || exit 1'
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    build:
      context: .
      dockerfile: Dockerfile.mariadb.coolify
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
