_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  autologout: 0
  automated_cron: 0
  ban: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  ckeditor_accordion: 0
  coffee: 0
  config: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dotenv: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  field: 0
  field_ui: 0
  file: 0
  file_delete: 0
  filter: 0
  focal_point: 0
  guardr_core: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  js_cookie: 0
  jsonapi: 0
  jsonapi_extras: 0
  jsonapi_image_styles: 0
  link: 0
  linkit: 0
  login_history: 0
  login_security: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  obfuscate_email: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pathologic: 0
  rapidkit_core: 0
  rapidkit_example: 0
  rapidkit_media_bundle: 0
  rapidkit_status_report: 0
  redirect: 0
  reroute_email: 0
  responsive_image: 0
  schema_metatag: 0
  seckit: 0
  security_review: 0
  serialization: 0
  session_limit: 0
  shortcut: 0
  svg_image: 0
  svg_image_responsive: 0
  symfony_mailer: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  twig_vardumper: 0
  update: 0
  upgrade_status: 0
  user: 0
  username_enumeration_prevention: 0
  views_ui: 0
  workflows: 0
  pathauto: 1
  password_policy: 10
  views: 10
  rapidkit_profile: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  rapidkit_theme: 0
  duchess: 0
profile: rapidkit_profile
